<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Show_customerLogin</name>
   <tag></tag>
   <elementGuidId>c0ab5895-2855-4ac0-8a57-7de9e8d8cc4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#customerLogin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='customerLogin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5abbe164-f4db-4cbb-bae6-8afebcf59138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c07e9564-bf24-455f-8d1e-f4f99322d961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn--full</value>
      <webElementGuid>21d742c3-437d-49d7-b1c4-7348d010d4b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customerLogin</value>
      <webElementGuid>1a894d29-b2d6-4322-9c80-3842bde61b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sign In</value>
      <webElementGuid>ba520844-b526-40f6-a57e-6207acc0d58b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customerLogin&quot;)</value>
      <webElementGuid>c672a589-2900-46c8-b583-e27798fe6649</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='customerLogin']</value>
      <webElementGuid>4c070dad-d7fd-41ac-a051-7bd2c73b85c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='customer_login']/p/input</value>
      <webElementGuid>63406b37-bb36-4521-8f9a-067a3ab77427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>9a3bcbee-1e17-45a3-9584-e45e9e79a09d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'customerLogin']</value>
      <webElementGuid>5f15c8a5-091a-4f8f-bd5a-4921d52657a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
