<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_FOOTWEAR</name>
   <tag></tag>
   <elementGuidId>25c1db42-f9c0-4db5-ba32-74e35c925c2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.site-nav__link.site-nav__link--has-dropdown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shopify-section-header']/div[2]/div/header/div/div/div[2]/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ce3d616f-b343-46dd-bd54-70952c009f1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/collections/footwear</value>
      <webElementGuid>e9afe82d-41a3-4318-a082-f12e8ae2f8d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>site-nav__link site-nav__link--has-dropdown</value>
      <webElementGuid>554c6343-de32-4aff-99ca-366034423b11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FOOTWEAR </value>
      <webElementGuid>b5d39355-6fff-4702-83e9-076d6f92601c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopify-section-header&quot;)/div[2]/div[@class=&quot;header-wrapper header-wrapper--overlay is-light&quot;]/header[@class=&quot;site-header&quot;]/div[@class=&quot;page-width&quot;]/div[@class=&quot;header-layout header-layout--right header-layout--mobile-logo-only&quot;]/div[@class=&quot;header-item header-item--navigation text-right small--hide&quot;]/ul[@class=&quot;site-nav site-navigation small--hide&quot;]/li[@class=&quot;site-nav__item site-nav__expanded-item site-nav--has-dropdown is-focused&quot;]/a[@class=&quot;site-nav__link site-nav__link--has-dropdown&quot;]</value>
      <webElementGuid>89109579-f444-470e-b9f6-fa2f575c541a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shopify-section-header']/div[2]/div/header/div/div/div[2]/ul/li/a</value>
      <webElementGuid>8b968384-69ab-4f1e-94e4-c7ca0e5e6e8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'FOOTWEAR')]</value>
      <webElementGuid>76048ebc-69ac-4056-ad4f-3c22ad11c31b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brodo'])[1]/following::a[3]</value>
      <webElementGuid>e7096eb8-2f05-4440-bd01-260f37160f59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ada promo harga spesial untuk Kamu. Ambil sekarang!'])[1]/following::a[4]</value>
      <webElementGuid>0e30d53d-7ad6-400d-9fff-ad4c8d644e6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[2]/preceding::a[1]</value>
      <webElementGuid>039bbace-f669-45e2-96b2-9c29fa2e8d5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sandals'])[2]/preceding::a[2]</value>
      <webElementGuid>c3133916-21cc-431c-84e4-49ac86729419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='FOOTWEAR']/parent::*</value>
      <webElementGuid>594a1398-8937-4fcb-b0a1-b7e43df80cb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/collections/footwear')])[2]</value>
      <webElementGuid>ffb3c3f9-553e-404b-8b6a-d546e92605ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/a</value>
      <webElementGuid>109696bf-5c93-455d-9e4c-bd9dc5697737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/collections/footwear' and (text() = 'FOOTWEAR ' or . = 'FOOTWEAR ')]</value>
      <webElementGuid>726ac35c-ee1b-46ad-843b-cf9d290cfd1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
